title: Joshua Lorincz
description: > # this means to ignore newlines until "baseurl:"
  I am a self-driven software engineer with experience in mobile, full-stack, and desktop application development. My passions are entrepreneurship, pathfinding research, and problem-solving in my community, yet my goal is always to learn. 
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://127.0.0.1:4000" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Joshua Lorincz
author-img: joshua-lorincz.jpeg
about-author: I am a <u>self-driven</u> software engineer with experience in mobile, full-stack, and desktop application development. My passions are entrepreneurship, pathfinding research, and problem-solving in my community, yet my <b>goal</b> is always to learn. 
social-twitter: # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: JoshLorDeveloper
social-linkedin: joshua-lorincz-242804155
social-email: joshlordeveloper@gmail.com

# Disqus
discus-identifier: JoshLor # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
